#!/usr/bin/env ruby

require File.dirname(__FILE__) + "/../config/rubundler"
r = Rubundler.new
r.setup_env

begin
  require File.dirname(__FILE__) + '/../lib/dm-salesforce'
rescue SystemExit => e
  if e.success?
    exit 0
  else
    puts "Got a SystemExit which was unexpected: #{e.message}"
    puts e.backtrace
    exit 2
  end
rescue Exception => e
  puts "Got an exception: #{e.class}, #{e.message}"
  puts e.backtrace
  exit 1
end
